    - name: Проверка установленной версии NetBackup
      ansible.builtin.stat:
        path: "/usr/openv/netbackup/bin/version"
      register: version_check

    - name: Пропустить установку, если NetBackup уже установлен
      ansible.builtin.debug:
        msg: "NetBackup уже установлен. Пропускаем дальнейшие действия."
      when: version_check.stat.exists

    - name: Проверка доступности установщика
      ansible.builtin.stat:
        path: "{{path_scripts}}"
      register: installer_stat
      when: not version_check.stat.exists  # Проверка только если NetBackup не установлен

    - name: Установка NB-clienta
      when:
        - installer_stat is defined
        - 'installer_stat.stat is defined'  # Проверка на существование атрибута stat
        - installer_stat.stat.exists
        - not version_check.stat.exists  # Проверка только если NetBackup не установлен

      ansible.builtin.expect:
        command: "{{path_scripts}}"
        responses:
          ".*Do you wish to continue?.*": "{{continue_installation}}\n"  # Продолжить установку?
          ".*Do you want to install the NetBackup client software for this client?.*": "{{continue_installation}}\n"  # Установить клиентское ПО NetBackup?
          ".*Enter the name of the NetBackup master server.*": "{{server_name}}\n"  # Введите имя главного сервера NetBackup
          ".*Would you like to use.*": "{{continue_installation}}\n"  # Хотите использовать?
          ".*Is this correct?.*": "{{continue_installation}}\n"  # Это правильно?
          ".*Enter the authorization token for bserv3.vimpelcom.ru or q to skip:.*": "{{token}}\n"  # Введите токен авторизации для bserv3.vimpelcom.ru или q для пропуска
          ".*You have used 1 of 3 attempts.*": "{{continue_installation}}\n"  # Вы использовали 1 из 3 попыток
          ".*Java GUI and JRE option:.*": "{{option}}\n"  # Опция для Java GUI и JRE
        timeout: 750
      register: installation_result

    - name: Проверка результата установки
      ansible.builtin.debug:
        var: installation_result
      when: not version_check.stat.exists  # Проверка только если NetBackup не установлен
      no_log: true  # Скрыть вывод

    - name: Stop NetBackup
      when:
        - installation_result is succeeded
        - not version_check.stat.exists
      ansible.builtin.command: "/usr/openv/netbackup/bin/goodies/netbackup stop"
      register: netbackup_stoped

    - name: Добавляем записи из внешнего файла в bp.conf
      when: not version_check.stat.exists  # Выполнить только если NetBackup не установлен
      ansible.builtin.lineinfile:
        path: /usr/openv/netbackup/bp.conf
        line: "{{ item }}"
        insertafter: '^SERVER'  # Вставить после строки, начинающейся со слова SERVER
      with_file: "{{ external_file }}"  # Путь к внешнему файлу с записями
      no_log: true  # Скрыть вывод добавляемых записей

    - name: Start NetBackup
      when: not version_check.stat.exists
      ansible.builtin.command: "/usr/openv/netbackup/bin/goodies/netbackup start"
      register: netbackup_started
